// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkgfaldyokxiinbuobzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZ2ZhbGR5b2t4aWluYnVvYnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzQ2OTksImV4cCI6MjA2NDUxMDY5OX0.8A5zQgKbOtmUebWWXKgfuPhfuY4a2dMSBupwPq9ZtpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);